config/routes.rb
Rails.application.routes.draw do
  # root "welcome#index"
  # get 'auth/github', as: :github_login
  # get '/auth/:provider/callback', to: 'sessions#create'
  # delete '/logout', as: :github_logout, to: 'sessions#destroy'
  # resources :users, only: [:show]

  root "welcome#index"
  get 'auth/github', as: :github_login
  get 'auth/:provider/callback', to: 'sessions#create'
  # get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', as: :github_logout, to: 'sessions#destroy'
  resources :users, only: [:show]
  # get '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/followed_user.rb
class FollowedUser < ApplicationRecord
  belongs_to :user
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user
end

app/models/starred_repo.rb
class StarredRepo < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_many :starred_repos
  has_many :followers
  has_many :followed_users

  def self.from_omniauth(auth)
    create! do |user|
      user.provider = auth[:provider]
      user.uid = auth[:uid]
      user.name = auth[:extra][:raw_info][:name]
      user.login = auth[:extra][:raw_info][:login]
      user.token = auth[:credentials][:token]
    end
  end

  def basic_info(profile_data)
    assign_attributes(avatar_url: profile_data[:avatar_url])
  end

  def assign_followers(follower_data)
    follower_data.each do |follower|
      Follower.find_or_create_by(follower_uid: follower[:id], name: follower[:login], user: self)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # helper_method :current_user
  #
  # def current_user
  #   @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  # end

  helper_method :current_user, :logged_in?

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    auth = request.env['omniauth.auth']

    user = User.find_by(provider: auth['provider'], uid: auth['uid']) || User.from_omniauth(auth)
    # user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    basic_data = Faraday.get("https://api.github.com/user?access_token=#{@user.token}")
    followers_data = Faraday.get("https://api.github.com/users/#{@user.login}/followers?access_token=#{@user.token}")
    @user.assign_followers(JSON.parse(followers_data.body, symbolize_names: true))
    @user.basic_info(JSON.parse(basic_data.body, symbolize_names: true))
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitlioBeta</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav>
    <ul>
      <li>
        <% if current_user %>
          <%= "Signed in as #{current_user.login}" %>
          <%= link_to "Logout", github_logout_path, method: :delete %>
        <% else %>
          <!-- <%= link_to "Login", '/auth/github' %> -->
        <% end %>
      </li>
      <% if current_user %>
        <li> <%= link_to "Your Profile", user_path(current_user) %> </li>
      <% end %>
    </ul>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/users/show.html.erb
<img class="img" src="<%= @user.avatar_url %>">
<nav class="inner-profile-nav">
  <ul>
    <li>Stars <%= @user.starred_repos.count %></li>
  </ul>
  <ul>
    <li>Followers <%= @user.followers.count %></li>
  </ul>
  <ul>
    <li>Following <%= @user.followed_users.count %></li>
  </ul>
</nav>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to "Login", '/auth/github' %>